### ISSUE TITLE
Remove Windows 7 from System Requirements

### ISSUE THREAD

**Issue by iNafeez** [LivePersonInc/knowledge-center-archive#151]
Hi Eden,

Please remove Windows 7 completely from our System Requirements page. End of Life from Microsoft announced and passed as of Jan 14, 2020. The URL to the page is: https://knowledge.liveperson.com/admin-settings-system-requirements.html#liveperson-workspace-requirements. 

The Microsoft link saying they ended Windows 7 here: https://support.microsoft.com/en-us/help/4057281/windows-7-support-ended-on-january-14-2020

**Comment by EdenKupe** [comment]
@cdougherty328 will take care of this

**Comment by cdougherty328** [comment]
Hi @iNafeez thanks for the update. Windows 7 has now been removed from the System Requirements.

**Comment by EdenKupe** [comment]
Hey @iNafeez 

Just wanted to point out that we reverted this change because it's incorrect. Windows 7's end of support simply means that Microsoft will simply no longer receive patches or support. You can still use Windows 7; it works.

Therefore, as long as a customer is using a supported browser, we support Windows 7. If you've told anyone else that we're no longer supporting Window 7, please correct.
