### ISSUE TITLE
Filter Chats by Date

### ISSUE THREAD

**Issue by sebpalmer** [LivePersonInc/knowledge-center-archive#168]
Hi there, our company uses liveperson to 'whatsapp' message many of our clients (some 6000 in total but far fewer actually active). Often, we need to open a chat in the agent workspace that has not had any activity for a few months and so accordingly change the date filter to further in the past (for instance, September 1st to December 1st). When we do this, the loading circle usually crops up indefinitely and by chance that it does load that right chats, once opened they do not show any chat history. This has become an increasingly difficult problem and we aren't sure how to progress as we often need to contact older clients.

How should we proceed with this?

**Comment by cshort-lp** [comment]
Hey @seb-stint there's lots of ways to go about this. 

> Often, we need to open a chat in the agent workspace that has not had any activity for a few months

In order to recommend something, I'd need to know more about _why_ you're needing to do this. Have you thought about importing chat history into a CRM for example? Or is there a reason that it needs to be viewed inside of the agent workspace in particular?

**Comment by sebpalmer** [comment]
Thank you for the reply! So the team (sort of a customer service type team) use the agent workspace as it is most user friendly and accessible. They message lots of people on a daily basis and a substantial number of the chats will not have had any activity in the past 3 months - prompting someone in the team to change the date filter which causes  a crash.

I'm not sure if this is the right platform to raise this issue but the problem is becoming quite untenable for the team.

**Comment by cshort-lp** [comment]
@seb-stint I'm not sure I understand the use case. Like is it so that agents can reach out and message customers again? Or just so they can read old convos for some reason?

Anyway, if it involves a crash, definitely talk to the support team. It's better that issues like crashes go through the proper channels

**Comment by sebpalmer** [comment]
Yep they need to access these chats for multiple reasons, sometimes just to read back on old conversations but mostly to re-start a conversation (either as an offer or to confirm details of something they've accepted). I've gone through the customer support team said there was nothing they could do and I've emailed our account rep but they are yet to reply. 

I'm not really where to turn now so any help would be greatly appreciated.

**Comment by cshort-lp** [comment]
@seb-stint Let me email you about this.
