### ISSUE TITLE
Wrong information on CSAT in the video

### ISSUE THREAD

**Issue by Mike-Z-DA** [LivePersonInc/knowledge-center-archive#37]
https://knowledge.liveperson.com/agent-manager-workspace-agent-tools-for-messaging-agent-workspace-for-messaging-tour.html

Instructor on the video on this page says that the CSAT score is "an average CSAT" for an agent.

In reality, it's a (total number of positive answers) / (total number of answers) which isn't a simple  CSAT average and could be understood differently.

**Comment by EdenKupe** [comment]
@lonz87 can you take a look at this?

**Comment by lonz87** [comment]
Copy of an email sent to our videographer:

Video: https://knowledge.liveperson.com/agent-manager-workspace-agent-tools-for-messaging-agent-workspace-for-messaging-tour.html

At 3:18 secs, Natalie says "and your average CSAT score". People have pointed out that it is not the average, rather a bit more complicated. Can you take out/dub the word "average" so Natalie just says "CSAT score"? 

Because this is a walkthrough of the agent workspace, we will be recording this video in a month or so, so not worth rerecording for one word.

**Comment by lonz87** [comment]
Video has been updated!

**Comment by Mike-Z-DA** [comment]
Thanks for help!
