### ISSUE TITLE
Proposed Changes in the Automatic Conversation Distribution document

### ISSUE THREAD

**Issue by Hmalchev** [LivePersonInc/knowledge-center-archive#71]
I have a proposed expansion and clarification of information for this document.
https://knowledge.liveperson.com/contact-center-management-live-chat-operations-automatic-conversation-distribution.html#how-acd-works
I propose that after this section "If both agents have the same load ratio, the chat is routed to the agent with the longest idle time. Idle time is determined by the time elapsed since the agent received the last chat" that this additional information be added:

-"Under "how ACD works", it says "If both agents have the same load ratio, the chat is routed to the agent with the longest idle time. Idle time is determined by the time elapsed since the agent received the last chat"."

-"I propose to add that agent states do not affect their place in queue, so for example if I am the next one to accept a chat but I moved to Away status and back to Online, it will not "reset" my idle time and  I will not be overtaken by the next agent in the queue."

**Comment by lonz87** [comment]
Thanks @Hmalchev . I have changed the paragraph to read like this:

"If both agents have the same load ratio, the chat is routed to the agent with the longest idle time. Idle time is determined by the time elapsed since the agent received the last chat. Note: Agent states do not impact their place in queue, so, for example, if the agent next in queue to accept a chat moved to 'Away' status and then back to 'Online', the change of state will not reset the agent's idle time."
